### PR TITLE
Add test for rendering transaction

### PR DESCRIPTION
**Pull request by bchallenor**
Covers fix for #37.

### CODE REVIEW

**Comment by bchallenor** [comment]
Not sure how you feel about the multiline raw string. It's inconsistent with the other tests, but the transaction is pretty unreadable without line breaks.

**Comment by twilco** [comment]
We use [indoc!](https://github.com/dtolnay/indoc) in [other multi-line tests in beancount-parse](https://github.com/twilco/beancount/blob/c0f614d700a3a96debdbbb756072ec2803d27cf5/beancount-parser/src/lib.rs#L1025-L1034), so I'd recommend that here as well.

**Comment by bchallenor** [comment]
Ah, I didn't realise you already had a dependency on indoc elsewhere. I've changed the test to use that.

**Comment by bchallenor** [comment]
Note in contrast to the indoc usages elsewhere:
1. I used a raw string to avoid having to escape the embedded quotes
2. I used curly brackets on the macro to protect it from rustfmt

**Comment by twilco** [comment]
Thanks again!

**Pull request merged**
