### PR TITLE
Render cost spec before price, not after

### LINKED ISSUE #37: beancount-render should render cost spec before price
If a posting has both a cost spec and a price, beancount-render currently renders the cost spec after the price.

I believe this is incorrect. bean-check cannot handle them this way round:
> syntax error, unexpected LCURLCURL, expecting EOL or COMMENT

Instead, beancount-render should render the cost spec before the price.

### PR DESCRIPTION
**Pull request by bchallenor**
This matches the grammar in beancount-parser.

Fixes #37

### CODE REVIEW

**Comment by twilco** [comment]
Thanks for this!

**Comment by twilco** [comment]
@bchallenor, I was too quick on the merge trigger-finger, but a follow-up PR with a test that would've failed before this PR would be great 🙂

**Comment by bchallenor** [comment]
I had a look at the render tests - while they cover many of the other directives, there don't seem to be any tests for transactions themselves. Should I add only the one regression test, or do you want more coverage than that?

**Comment by twilco** [comment]
Ahh, we could definitely use some test coverage for transactions, so I'll take however much you're able to offer.

**Pull request merged**
